FROM nginx:alpine

RUN apk add --no-cache openssl && \
    mkdir -p /etc/nginx/certs && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout /etc/nginx/certs/selfsigned.key \
      -out    /etc/nginx/certs/selfsigned.crt \
      -subj   "/C=ES/ST=Madrid/L=Madrid/O=MMStudio/CN=localhost"

COPY nginx.local.conf /etc/nginx/conf.d/default.conf

COPY . /usr/share/nginx/html

EXPOSE 80 443
